<a href="https://colab.research.google.com/github/shivanshgarg22/shivansh_102317207-Optimus_prime/blob/main/Shivansh_102317207_assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1->

In [1]:
import numpy as np
a=np.array([3,3,4,7])
print(a+5)
print(a*5)
print(a/3)

[ 8  8  9 12]
[15 15 20 35]
[1.         1.         1.33333333 2.33333333]


Q2->

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
max_count = counts.max()
mode_values = values[counts == max_count]

# Most frequent value and their indices
mode_x = mode_values[0]
indices_x = np.where(x == mode_x)[0]
print("Most frequent values =", mode_x)
print("Their values =", indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
max_count = counts.max()
mode_values = values[counts == max_count]

# Most frequent values and their indices
modes_indices_y = [(val, np.where(y == val)[0]) for val in mode_values]
print(modes_indices_y)
print(mode_values)

[5 4 6 3 2 1]
Most frequent values = 1
Their values = [0 5 7 8 9]
[(1, array([0, 1, 2])), (3, array([4, 8, 9]))]
[1 3]


Q3->

In [3]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Access 1st row, 2nd column
element_1 = arr[0, 1]  # Accessing element at row index 0 and column index 1
print(f"Element at 1st row, 2nd column: {element_1}")

# b) Access 3rd row, 1st column
element_2 = arr[2, 0]  # Accessing element at row index 2 and column index 0
print(f"Element at 3rd row, 1st column: {element_2}")

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q4->

In [4]:
import numpy as np
shivansh = np.linspace(10, 100, 25)
print("Array: ",shivansh)
print("Dimensions: ",shivansh.ndim)
print("Shape: ",shivansh.shape)
print("Total elements: ",shivansh.size)
print("Data type of each element: ",shivansh.dtype)
print("Bytes consumed by the array: ",shivansh.nbytes)

transpose_array=shivansh.reshape(25,1)
print("Transpose of the array using reshape\n: ",transpose_array)
print("Using T attribute: ",shivansh.T)
print("Shape after .T: ",shivansh.T.shape)

Array:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions:  1
Shape:  (25,)
Total elements:  25
Data type of each element:  float64
Bytes consumed by the array:  200
Transpose of the array using reshape
:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape after .T:  (25,)


Q5->

In [5]:
import numpy as np

shivansh = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])

mean_value = np.mean(shivansh)
median_value = np.median(shivansh)
max_value = np.max(shivansh)
min_value = np.min(shivansh)
unique_elements = np.unique(shivansh)

print("Original 2D Array:\n", shivansh)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max Value:", max_value)
print("Min Value:", min_value)
print("Unique Elements:", unique_elements)

reshapedshivansh = shivansh.reshape(4, 3)
print("\nReshaped (4x3) Array:\n", shivansh)

reshapedshivansh = np.resize(shivansh, (2, 3))
print("\nResized (2x3) Array:\n", reshapedshivansh)


Original 2D Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max Value: 90
Min Value: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3) Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Resized (2x3) Array:
 [[10 20 30]
 [40 50 60]]
